version: "3"
services:
  es:
    build: es
    image: registry.cn-beijing.aliyuncs.com/wangdali/es-with-ik:6.2.2
    user: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "./es/data:/usr/share/elasticsearch/data"
      - "./es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"